INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO)
VALUES (5,'Engenharia de Computação',NULL);
-- COMMIT implícito
SELECT * FROM CURSO; -- Dados atuais
BEGIN;
INSERT INTO CURSO (CODIGOCURSO,NOME,DATACRIACAO) VALUES (6,'Psicologia',NULL);
SELECT * FROM CURSO; -- Dados após inserção
ROLLBACK;
END;
SELECT * FROM CURSO; -- Dados após desfazer a transação
SELECT * FROM DISCIPLINA;
BEGIN;
UPDATE DISCIPLINA SET CARGAHORARIA=CARGAHORARIA*1.2 WHERE CARGAHORARIA=60;
SELECT * FROM DISCIPLINA;
UPDATE DISCIPLINA SET CARGAHORARIA=CARGAHORARIA*1.1 WHERE CARGAHORARIA=40;
SELECT * FROM DISCIPLINA;
COMMIT;
BEGIN;
UPDATE DISCIPLINA SET CARGAHORARIA=CARGAHORARIA*1.2 WHERE CARGAHORARIA=60;
SELECT * FROM DISCIPLINA;
SAVEPOINT CARGA60;
UPDATE DISCIPLINA SET CARGAHORARIA=CARGAHORARIA*1.1 WHERE CARGAHORARIA=40;
ROLLBACK TO CARGA60;
SELECT * FROM DISCIPLINA;
COMMIT;
BEGIN;
SET TRANSACTION READ ONLY;
SELECT * FROM CURSODISCIPLINA;
DROP TABLE CURSODISCIPLINA;
ROLLBACK;
