CREATE DATABASE BDESTUDO;
DROP DATABASE BDESTUDO;
CREATE TABLE NIVEL (
CODIGONIVEL int NOT NULL,
DESCRICAO char(90) NOT NULL,
CONSTRAINT CHAVEPNIVEL PRIMARY KEY (CODIGONIVEL));
CREATE TABLE CURSO (
CODIGOCURSO int NOT NULL,
NOME char(90) NOT NULL UNIQUE,
DATACRIACAO date NULL,
CODIGONIVEL int NULL,
CONSTRAINT CHAVEPCURSO PRIMARY KEY (CODIGOCURSO),
FOREIGN KEY (CODIGONIVEL) REFERENCES NIVEL (CODIGONIVEL)
);
CREATE DATABASE TESTEBANCO
SELECT OID, DATNAME FROM PG_DATABASE;
ALTER TABLE CURSO ADD DTRECONH DATE;
ALTER TABLE CURSO DROP DTRECONH ;
DROP TABLE CURSO;
CREATE TABLE NIVEL (
CODIGONIVEL int NOT NULL,
DESCRICAO char(90) NOT NULL,
CONSTRAINT CHAVEPNIVEL PRIMARY KEY (CODIGONIVEL));
CREATE TABLE CURSO (
CODIGOCURSO int NOT NULL,
NOME char(90) NOT NULL UNIQUE,
DATACRIACAO date NULL,
CODIGONIVEL int NULL,
FOREIGN KEY (CODIGONIVEL) REFERENCES NIVEL (CODIGONIVEL)
);
ALTER TABLE CURSO ADD FOREIGN KEY (CODIGONIVEL) REFERENCES NIVEL;
DROP TABLE NIVEL;
DROP TABLE NIVEL CASCADE;
/*
